services:

  webapp:
    build: .
    image: forseer/forum-backend:latest
    command: gunicorn -b :8000 app:app
    ports:
      - "5001:8000"
    networks:
      - app-tier
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - app-tier
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mydata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-tier:
    driver: bridge

volumes:
  postgres_data: