name: "ForUm_BackEnd"
services:
  webapp:
    image: fastapi_forum
    ports:
      - "5001:8000"
    networks:
      - app-tier
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - app-tier
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mydata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydata"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-tier:
    driver: bridge
